moodle:
  base_url: "https://ava.ufscar.br"
  username: 75329
  class_id: 23133

evidences:
  consolidation:
    - title: "P1"
      gradebook_name: "P1 total"
      deadline_quiz_id: 1147860

  monitoring:
    - title: "L1"
      quiz_id: 1147861
    - title: "L2"
      quiz_id: 1147862
    - title: "L3"
      quiz_id: 1147863
